import { Car } from "@/types/types";

// write data
export const initialCars = [
  {
    make: "Ford",
    model: "Fusion",
    year: 2019,
    color: "Black",
    body: "Sedan",
    transmission: "Automatic",
    driveType: "FWD",
    fuelType: "Gasoline",
  },
  {
    make: "Chevy",
    model: "Malibu",
    year: 2020,
    color: "Red",
    body: "Coupe",
    transmission: "Automatic",
    driveType: "AWD",
    fuelType: "Electric",
  },
  {
    make: "Toyota",
    model: "Camry",
    year: 2021,
    color: "White",
    body: "SUV",
    transmission: "Manual",
    driveType: "RWD",
    fuelType: "Hybrid",
  },
  {
    make: "Honda",
    model: "Civic",
    year: 2018,
    color: "Blue",
    body: "Hatchback",
    transmission: "Automatic",
    driveType: "FWD",
    fuelType: "Diesel",
  },
  {
    make: "Nissan",
    model: "Altima",
    year: 2017,
    color: "Gray",
    body: "Convertible",
    transmission: "Manual",
    driveType: "AWD",
    fuelType: "Gasoline",
  },
  {
    make: "Ford",
    model: "Fusion",
    year: 2019,
    color: "Black",
    body: "Sedan",
    transmission: "Automatic",
    driveType: "FWD",
    fuelType: "Gasoline",
  },
  {
    make: "Chevy",
    model: "Malibu",
    year: 2020,
    color: "Red",
    body: "Coupe",
    transmission: "Automatic",
    driveType: "AWD",
    fuelType: "Electric",
  },
  {
    make: "Toyota",
    model: "Camry",
    year: 2021,
    color: "White",
    body: "SUV",
    transmission: "Manual",
    driveType: "RWD",
    fuelType: "Hybrid",
  },
  {
    make: "Honda",
    model: "Civic",
    year: 2018,
    color: "Blue",
    body: "Hatchback",
    transmission: "Automatic",
    driveType: "FWD",
    fuelType: "Diesel",
  },
  {
    make: "Nissan",
    model: "Altima",
    year: 2017,
    color: "Gray",
    body: "Convertible",
    transmission: "Manual",
    driveType: "AWD",
    fuelType: "Gasoline",
  },
] as Car[];
