import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";

// jmeter -n -t load-test/lots_of_rentals.jmx -l load-test/results/demo_results.jtl -e -o load-test/results/demo_results_temp

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "MPP Project",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
