"use client";

import { useEffect, useState } from "react";
import RentalDateRange from "./RentalDateRange";
import { getRevenueInTimeFrame } from "@/service/RentalsService";
import {
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  Legend,
  ResponsiveContainer,
} from "recharts";

interface RentalRevenue {
  id: number;
  make: string;
  model: string;
  revenue: number;
}

interface CustomTooltipProps {
  active?: boolean;
  payload?: any[];
  label?: string;
}

const CustomTooltip: React.FC<CustomTooltipProps> = ({ active, payload }) => {
  if (active && payload && payload.length) {
    return (
      <div className="custom-tooltip p-2 bg-white border border-gray-200 shadow-lg rounded">
        <p className="label font-semibold">{`Make: ${payload[0].payload.make}`}</p>
        <p className="intro">{`Model: ${payload[0].payload.model}`}</p>
        <p className="desc">{`Revenue: $${payload[0].value}`}</p>
      </div>
    );
  }

  return null;
};

export default function RevenueComponent() {
  const [rentalsRevenue, setRentalsRevenue] = useState<RentalRevenue[]>([]);
  const [startDate, setStartDate] = useState<string>("2021-01-01");
  const [endDate, setEndDate] = useState<string>(
    new Date().toISOString().split("T")[0],
  );

  useEffect(() => {
    const fetchRevenue = async () => {
      const res = await getRevenueInTimeFrame(startDate, endDate);
      setRentalsRevenue(res);
    };
    fetchRevenue();
  }, [startDate, endDate]);

  return (
    <div className="pt-10 px-6 max-w-7xl mx-auto">
      <h1 className="text-2xl font-bold text-center mb-6">
        Rental Revenue Analysis
      </h1>
      <p className="text-center mb-10 text-gray-600">
        Select a date range to view the revenue generated by each car make and
        model.
      </p>
      <div className="mb-10">
        <RentalDateRange
          startDate={startDate}
          setStartDate={setStartDate}
          endDate={endDate}
          setEndDate={setEndDate}
        />
      </div>
      <div className="bg-white p-6 rounded-lg shadow-lg">
        <ResponsiveContainer width="100%" height={400}>
          <BarChart
            width={500}
            height={300}
            data={rentalsRevenue}
            margin={{
              top: 5,
              right: 30,
              left: 20,
              bottom: 5,
            }}
          >
            <CartesianGrid strokeDasharray="3 3" />
            <XAxis dataKey="make" />
            <YAxis />
            <Tooltip content={<CustomTooltip />} />
            <Legend />
            <Bar dataKey="revenue" fill="var(--primary-color)" />
          </BarChart>
        </ResponsiveContainer>
      </div>
    </div>
  );
}
