name: Lint

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run-linters:
    name: run-linters
    runs-on: ubuntu-latest

    steps:
      - name: Set up pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: pnpm install

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
          prettier: true
